### ISSUE TITLE
Error in results: missing TRUE/FALSE value?!

### ISSUE THREAD

**Issue by bemacedom** [massimoaria/bibliometrix#67] opened 2019-08-14 20:44 UTC
I'm having some trouble to do my research of bibliometric with bibliometrix on R. 
I've already made a lot of time, using the same code i found the error on **results** part: **Error in if (sum(ind > -1) > 0) { :**
It says that is missing the TRUE/FALSE value, but at this part don't need it. 
I have sure that i'm doing all the things right and didn't found nothing on web about this error. 
Have someone already found this error? Anyone can help me? 

`> library("bibliometrix")
To cite bibliometrix in publications, please use:
  
  Aria, M. & Cuccurullo, C. (2017) bibliometrix: An R-tool for comprehensive science mapping analysis, Journal of Informetrics, 11(4), pp 959-975, Elsevier.

http:\\www.bibliometrix.org

To start with the shiny web-interface, please digit:
  biblioshiny()
> DS <- readFiles (file = "C:/Users/_/Documents/bibliometrix/sco1.bib", "C:/Users/_/Documents/bibliometrix/sco3.bib", "C:/Users/_/Documents/bibliometrix/sco4.bib", "C:/Users/_/Documents/bibliometrix/sco5.bib", "C:/Users/_/Documents/bibliometrix/sco6.bib", "C:/Users/_/Documents/bibliometrix/sco7.bib", "C:/Users/_/Documents/bibliometrix/sco8.bib", "C:/Users/_/Documents/bibliometrix/sco9.bib", "C:/Users/_/Documents/bibliometrix/sco10.bib")
> DW <- readFiles (file = "C:/Users/_/Documents/bibliometrix/wos1.bib", "C:/Users/_/Documents/bibliometrix/wos3.bib", "C:/Users/_/Documents/bibliometrix/wos4.bib", "C:/Users/_/Documents/bibliometrix/wos5.bib", "C:/Users/_/Documents/bibliometrix/wos7.bib", "C:/Users/_/Documents/bibliometrix/wos8.bib", "C:/Users/_/Documents/bibliometrix/wos9.bib", "C:/Users/_/Documents/bibliometrix/wos10.bib")
> M1 <- convert2df(DS, dbsource = "scopus", format = "bibtex")

Converting your scopus collection into a bibliographic dataframe

Articles extracted   100 
Articles extracted   200 
Articles extracted   280 
Done!

Generating affiliation field tag AU_UN from C1:  Done!

> M2 <- convert2df(DW, dbsource = "isi", format = "bibtex")

Converting your isi collection into a bibliographic dataframe

Articles extracted   100 
Articles extracted   200 
Articles extracted   211 
Done!

> M <- mergeDbSources(M1, M2, remove.duplicated = TRUE)

 395 duplicated documents have been removed
> dim(M)
[1] 96 19
> results <- biblioAnalysis(M, sep = ";")
Error in if (sum(ind > -1) > 0) { : 
  valor ausente onde TRUE/FALSE necessário
> 
`

**Comment by massimoaria** [comment] 2019-08-19 10:10
The issue is due to mergeDbSources function that is yet in a developer version.
The merging of WOS and SCOPUS DBs is tremendous task because some critical fields are codified in very different ways (Author names, Affiliations, Cited references). Moreover, in Scopus cited reference items are not standardized so they need to be matched (e.g., In a Scopus collection of 2,000 documents about “classification trees”, the famous book by Brieman et al., 1984, “Classification and Regression Trees”, is cited in 396 different ways!).
We are working hard on a set of merging-oriented functions that will be deployed in the next months.

**Closed** 2021-01-18 13:57 UTC
